### ISSUE TITLE
Privacy Manifest, the privacy report of a SDK will not be displayed

### ISSUE THREAD

**Issue by wlxo0401** [yene/GCDWebServer#7]
Thank you always for your quick response.

![1](https://github.com/yene/GCDWebServer/assets/57979066/10d1feb2-5430-4477-95b6-30100867b1ab)
I checked that Privacy Manifest was included, but it seems that the results of the archive are not included in the Privacy Report.

<img width="984" alt="289769661-30d7379e-ee26-4a2d-8800-98b7ea3fc69e" src="https://github.com/yene/GCDWebServer/assets/57979066/d7c456c4-3652-431a-995b-9775cacd8e16">
When I check the library file, Privacy Manifest exists in 'ZIPFoundation' and 'GCDWebServer', but only 'ZIPFoundation' exists in Privacy Report.

**Comment by wlxo0401** [comment]
[ZIPFoundation PR](https://github.com/weichsel/ZIPFoundation/commit/5559b823c19aceb659387b452915d099c542a0a0)

![스크린샷 2023-12-20 오후 4 33 33](https://github.com/yene/GCDWebServer/assets/57979066/dd998196-b703-42bd-a489-c17d19b3f268)
I tried similarly by looking at the commit applied by ZIPFoundation, but it also doesn't recognize it.

Will this problem happen without '.xcodeproj'? It's hard..

I don't know what the problem is.

**Comment by yene** [comment]
yes, the file needed to be copied in. It will not show up in the report because it tracks nothing.
